help:
	@echo "    install"

install:
	pip install cytoolz-0.9.0.1-cp36-cp36m-win_amd64.whl &&
	pip install JPype1-0.6.3-cp36-cp36m-win_amd64.whl &&
	pip install python_Levenshtein-0.12.0-cp36-cp36m-win_amd64.whl &&
	pip install SQLAlchemy-1.2.14-cp36-cp36m-win_amd64.whl &&
	pip install ujson-1.35-cp36-cp36m-win_amd64.whl &&
	pip install wrapt-1.10.11-cp36-cp36m-win_amd64.whl  
